In [3]:
import os
from pathlib import Path
import pickle
from helper import *

import warnings
warnings.filterwarnings('ignore')

In [6]:
def load_pickle(file_path:Path):
# Load the pickled tokenizer
    with open(file_path, 'rb') as file:
        loaded_file = pickle.load(file)
    return loaded_file

In [26]:
rnn_model_path = Path('models/model_checkpoint_RNN.h5')
lstm_model_path = Path('models/model_checkpoint_LSTM.h5')
gru_model_path = Path('models/model_checkpoint_GRU.h5')

In [5]:
preProccessor_path = Path('preprocessor/tokenizer.pkl') 

In [12]:
tokenizer = load_pickle(preProccessor_path)

In [9]:
import tensorflow as tf

In [27]:
rnn_model = tf.keras.models.load_model(rnn_model_path)
lstm_model = tf.keras.models.load_model(lstm_model_path)
gru_model = tf.keras.models.load_model(gru_model_path)

In [11]:
test = {"article_link": "https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5",
    "headline": "former versace store clerk sues over secret 'black code' for minority shoppers", "is_sarcastic": 0},

In [18]:
test_case = [
    "former versace store clerk sues over secret 'black code' for minority shoppers"]

In [19]:
clean_test_case = clean_data(test_case)

In [20]:
clean_test_case

['former versac store clerk sue secret black code minor shopper']

In [21]:
test_padded_seq = to_sequences_n_padding(tokenizer,
                                         MAX_LENGTH=MAX_LENGTH,
                                         PADDING_TYPE=PADDING_TYPE,
                                         TRUNC_TYPE=TRUNC_TYPE,
                                         X_data=clean_test_case)

In [22]:
test_padded_seq

array([[ 296,    1,  505, 2854, 1354,  261,   57, 2024, 1337, 5143,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0]])

In [23]:
lstm_model.predict(test_padded_seq)

1/1 [==============================] - 7s 7s/step


array([[0.19541991]], dtype=float32)

In [24]:
rnn_model.predict(test_padded_seq)

1/1 [==============================] - 1s 850ms/step


array([[0.41289568]], dtype=float32)

In [28]:
gru_model.predict(test_padded_seq)

1/1 [==============================] - 2s 2s/step


array([[0.23457493]], dtype=float32)